### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Sumanth-143** [Jaidev-rawat/FOOD_APP#1]
Bro May I know the source of the dataset

**Comment by Jaidev-rawat** [comment]
From kaggle and Google...
I had taken different datasets from kaggle and also made most of the image classes by myself from google and merged all of them together.

**Comment by Sumanth-143** [comment]
Github bro😉

**Comment by Sumanth-143** [comment]
I found the dataset but it is having only 20 classes. But ur having 43 i
guess

**Comment by Jaidev-rawat** [comment]
Yes, as far as I know you won't find 43 clasess of this dataset at one place, It took me more than 10 days to collect different classes from different sources, I also Downloaded a lot and lot of images from google to increase my number of classses, more than 30% of my time was taken us by this data collection, cleaning and formating only.

**Comment by Sumanth-143** [comment]
Ohh..that's great bro.
Do u have that dataset of all those classes?

**Comment by Sumanth-143** [comment]
Bro please do reply.

**Comment by Jaidev-rawat** [comment]
Size too large can't upload 😅
Downlaod_dataset.ipynb has 80% of the data source, try that.

**Comment by Sumanth-143** [comment]
U can share me the link of that  bro if you don't mind.
Or else via telegram: 8919237387
I think u have uploaded to ur drive .

Thanks & Regards
Sumanth

**Comment by Sumanth-143** [comment]
What happened bro?
Don't wanna help me?
